# Generated by Django 5.2 on 2025-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_favoritepaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="category",
            field=models.CharField(
                choices=[
                    ("notes", "Notes"),
                    ("exams", "Past Exam Questions"),
                    ("general", "General"),
                ],
                default="general",
                max_length=10,
            ),
        ),
    ]
