# Generated by Django 5.2 on 2025-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_papers',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='myapp.paper'),
        ),
    ]
